// <auto-generated />
namespace DestCovery.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
<<<<<<< HEAD:16-03-2020/DestCovery/Migrations/202003160356133_Database_creation.Designer.cs
    public sealed partial class Database_creation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Database_creation));
        
        string IMigrationMetadata.Id
        {
            get { return "202003160356133_Database_creation"; }
=======
    public sealed partial class Migration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Migration));
        
        string IMigrationMetadata.Id
        {
            get { return "202003160444084_Migration"; }
>>>>>>> cf03d1cbbe5c4854f254ac9cac394452dd690fa9:DestCovery/DestCovery/Migrations/202003160444084_Migration.Designer.cs
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
