// <auto-generated />
namespace DestCovery.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class bool_chng : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(bool_chng));
        
        string IMigrationMetadata.Id
        {
            get { return "202003291227562_bool_chng"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
