//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DestCovery.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Booking
    {
        [Key]
        public int Booking_Id { get; set; }
        public int Package_Id { get; set; }
        public int Tour_Id { get; set; }
        public int User_Id { get; set; }
        public int Persons_Enrolled { get; set; }
        public decimal Price_Per_Person { get; set; }
        public decimal Estimated_Price { get; set; }
        public System.DateTime Booking_Date { get; set; }
        public bool Booking_Status { get; set; }
        public Nullable<int> fk_for_Spot_Id_Spot_Id { get; set; }
    
        public virtual Package_Master Package_Master { get; set; }
        public virtual Package_Spots Package_Spots { get; set; }
        public virtual Package_Tour Package_Tour { get; set; }
    }
}
