//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DestCovery.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DestCoveryContextEntities1 : DbContext
    {
        public DestCoveryContextEntities1()
            : base("name=DestCoveryContextEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin_Info> Admin_Info { get; set; }
        public virtual DbSet<Booking> Bookings { get; set; }
        public virtual DbSet<Package_Grid_Image> Package_Grid_Image { get; set; }
        public virtual DbSet<Package_Master> Package_Master { get; set; }
        public virtual DbSet<Package_Review> Package_Review { get; set; }
        public virtual DbSet<Package_Spots> Package_Spots { get; set; }
        public virtual DbSet<Package_Tour> Package_Tour { get; set; }
        public virtual DbSet<User_Info> User_Info { get; set; }
    }
}
