//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DestCovery.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Package_Grid_Image
    {
        [Key]
        public int Package_GridImg_Id { get; set; }
        public int Package_Id { get; set; }
        public string Package_GridImg { get; set; }
    
        public virtual Package_Master Package_Master { get; set; }
    }
}
