// <auto-generated />
namespace DestCovery.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Database_creation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Database_creation));
        
        string IMigrationMetadata.Id
        {
            get { return "202003160356133_Database_creation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
